### ISSUE TITLE
Match functionality across the 3 APIs

### ISSUE THREAD

**Issue by bfred-it** [rollup/rollup#1461]
### Missing from the programmatic API

- [ ] Support for `--watch`
- [ ] Support for config files (`--config rollup.config.js`) https://github.com/rollup/rollup/issues/761
- [ ] Support arrays of configs https://github.com/rollup/rollup/issues/1460

### Missing from the command line / CLI

- [ ] Enable plugins via parameter https://github.com/rollup/rollup/issues/1304 (+ ancient https://github.com/rollup/rollup/issues/226)

What else is missing?

**Comment by guybedford** [comment]
I believe all of these are resolved except for #1304, so probably worth continuing to track there. But do let me know if I'm mistaken on this.

**Comment by bfred-it** [comment]
@guybedford only `rollup.watch()` seems to be in there, the rest isn't.

Config options still don't have the same API, it seems. Is this possible?

```js
rollup.generate(await fs.readFile('./rollup.config.js'))
```

**Comment by guybedford** [comment]
@bfred-it sure, I've reopened #761 to track.
